In [4]:
import numpy as np
import cobra
import pandas

model = cobra.io.read_sbml_model("1752-0509-4-31-S2_cobra.xml")

In [5]:
print(len(model.reactions))
print(len(model.metabolites))
print(len(model.compartments))
print(model.compartments)
print(len(model.exchanges))

print(model.objective)

631
594
2
{'e': '', 'c': ''}
52
Maximize
1.0*R_BIOMASS - 1.0*R_BIOMASS_reverse_6575a

In [6]:
model.exchanges

[<Reaction EX_ca2_e at 0x7f9519f26e70>,
 <Reaction EX_cellulose_e at 0x7f9519f27020>,
 <Reaction EX_no2_e at 0x7f9519f26f60>,
 <Reaction EX_fru_e at 0x7f9519f26f90>,
 <Reaction EX_pnto-r_e at 0x7f9519f270b0>,
 <Reaction EX_h2o_e at 0x7f9519f27140>,
 <Reaction EX_for_e at 0x7f9519f271a0>,
 <Reaction EX_lac-l_e at 0x7f9519f271d0>,
 <Reaction EX_nh4_e at 0x7f9519f272c0>,
 <Reaction EX_ac_e at 0x7f9519f27230>,
 <Reaction EX_pi_e at 0x7f9519f27080>,
 <Reaction EX_h2s_e at 0x7f9519f273e0>,
 <Reaction EX_cellobiose_e at 0x7f9519f27470>,
 <Reaction EX_succ_e at 0x7f9519f27500>,
 <Reaction EX_so4_e at 0x7f9519f27560>,
 <Reaction EX_gcald_e at 0x7f9519f27590>,
 <Reaction EX_k_e at 0x7f9519f274a0>,
 <Reaction EX_h2_e at 0x7f9519f275f0>,
 <Reaction EX_co2_e at 0x7f9519f276e0>,
 <Reaction EX_nmn_e at 0x7f9519f27770>,
 <Reaction EX_h_e at 0x7f9519f27200>,
 <Reaction EX_fe3_e at 0x7f9519f27860>,
 <Reaction EX_etoh_e at 0x7f9519f278c0>,
 <Reaction EX_mg2_e at 0x7f951a0e4fe0>,
 <Reaction EX_pyr_e at 0x7f9519f279b0>,
 <Reaction EX_xyl-d_e at 0x7f9519f279e0>,
 <Reaction EX_rib-d_e at 0x7f9519f27a40>,
 <Reaction EX_glyc_e at 0x7f9519f27aa0>,
 <Reaction EX_mal-l_e at 0x7f9519f27b00>,
 <Reaction EX_cit_e at 0x7f9519f27b60>,
 <Reaction EX_fum_e at 0x7f9519f27bc0>,
 <Reaction EX_akg_e at 0x7f9519f27c20>,
 <Reaction EX_ala-l_e at 0x7f9519f27c80>,
 <Reaction EX_arg-l_e at 0x7f9519f27ce0>,
 <Reaction EX_asn-l_e at 0x7f9519f27d40>,
 <Reaction EX_asp-l_e at 0x7f9519f27da0>,
 <Reaction EX_cys-l_e at 0x7f9519f27e00>,
 <Reaction EX_glu-l_e at 0x7f9519f27e60>,
 <Reaction EX_gln-l_e at 0x7f9519f27ec0>,
 <Reaction EX_gly_e at 0x7f9519f27f20>,
 <Reaction EX_his-l_e at 0x7f9519f26e40>,
 <Reaction EX_ile-l_e at 0x7f9519f27fe0>,
 <Reaction EX_leu-l_e at 0x7f9519f27f80>,
 <Reaction EX_lys-l_e at 0x7f9519f27fb0>,
 <Reaction EX_met-l_e at 0x7f9519f27cb0>,
 <Reaction EX_phe-l_e at 0x7f9519f27950>,
 <Reaction EX_pro-l_e at 0x7f9519f27c50>,
 <Reaction EX_ser-l_e at 0x7f9519f27980>,
 <Reaction EX_thr-l_e at 0x7f951a3c36e0>,
 <Reaction EX_trp-l_e at 0x7f9519f602c0>,
 <Reaction EX_tyr-l_e at 0x7f9519f60320>,
 <Reaction EX_val-l_e at 0x7f9519f60380>]

In [7]:
sol=model.optimize()
model.summary()

In [8]:
#cellubiose
with model:
    model.objective = 'R_BIOMASScell'
    model.reactions.EX_cellulose_e.lower_bound = 0
    model.reactions.EX_cellulose_e.upper_bound = 0
    model.reactions.EX_cellobiose_e.lower_bound = -2.2472
    model.reactions.EX_cellobiose_e.upper_bound = -2.2472
    model.reactions.EX_fru_e.lower_bound = 0
    model.reactions.EX_fru_e.upper_bound = 0
    sol=model.optimize()
    print(model.summary())

Objective
=========
1.0 R_BIOMASScell = 0.09394901517067404

Uptake
------
  Metabolite        Reaction      Flux  C-Number C-Flux
       ca2_e        EX_ca2_e 0.0003006         0  0.00%
cellobiose_e EX_cellobiose_e     2.247         0  0.00%
       fe3_e        EX_fe3_e 0.0003194         0  0.00%
       h2s_e        EX_h2s_e   0.01399         0  0.00%
         k_e          EX_k_e   0.06636         0  0.00%
       mg2_e        EX_mg2_e  0.009555         0  0.00%
       nh4_e        EX_nh4_e    0.8628         0  0.00%
       nmn_e        EX_nmn_e  0.001625         0  0.00%
        pi_e         EX_pi_e    0.1993         0  0.00%

Secretion
---------
Metabolite      Reaction     Flux  C-Number C-Flux
      ac_e       EX_ac_e   -7.649         0  0.00%
cellmass_c EX_cellmass_c -0.09395         0  0.00%
     co2_e      EX_co2_e   -7.898         0  0.00%
      h2_e       EX_h2_e   -11.16         0  0.00%
     h2o_e      EX_h2o_e   -6.039         0  0.00%

In [15]:
#cellubiose+acetate
with model:
    model.objective = 'R_BIOMASScell'
    model.reactions.EX_cellulose_e.lower_bound = 0
    model.reactions.EX_cellulose_e.upper_bound = 0
    model.reactions.EX_cellobiose_e.lower_bound = -2.2472
    model.reactions.EX_cellobiose_e.upper_bound = -2.2472
    model.reactions.EX_fru_e.lower_bound = 0
    model.reactions.EX_fru_e.upper_bound = 0
    model.reactions.EX_ac_e.lower_bound = 2.457
    model.reactions.EX_ac_e.upper_bound = 2.457
    sol=model.optimize()
    print(model.summary())

Objective
=========
1.0 R_BIOMASScell = 0.07626024289395522

Uptake
------
  Metabolite        Reaction      Flux  C-Number C-Flux
       ca2_e        EX_ca2_e  0.000244         0  0.00%
cellobiose_e EX_cellobiose_e     2.247         0  0.00%
       fe3_e        EX_fe3_e 0.0002593         0  0.00%
       h2s_e        EX_h2s_e   0.01136         0  0.00%
         k_e          EX_k_e   0.05386         0  0.00%
       mg2_e        EX_mg2_e  0.007756         0  0.00%
       nh4_e        EX_nh4_e    0.7003         0  0.00%
       nmn_e        EX_nmn_e  0.001319         0  0.00%
        pi_e         EX_pi_e    0.1618         0  0.00%

Secretion
---------
Metabolite      Reaction     Flux  C-Number C-Flux
      ac_e       EX_ac_e   -2.457         0  0.00%
cellmass_c EX_cellmass_c -0.07626         0  0.00%
     co2_e      EX_co2_e   -8.103         0  0.00%
    etoh_e     EX_etoh_e   -1.865         0  0.00%
      h2_e       EX_h2_e   -11.09         0  0.00%
     h2o_e      EX_h2o_e   -4.651         0  0.00%
    succ_e     EX_succ_e    -1.79         0  0.00%

In [10]:
#fructose (note:different objective)
with model:
    model.objective= 'R_BIOMASS'
    model.reactions.EX_cellulose_e.lower_bound = 0
    model.reactions.EX_cellulose_e.upper_bound = 0
    model.reactions.EX_cellobiose_e.lower_bound = 0
    model.reactions.EX_cellobiose_e.upper_bound = 0
    model.reactions.EX_fru_e.lower_bound = -6.0961
    model.reactions.EX_fru_e.upper_bound = -6.0961
    sol=model.optimize()
    print(model.summary())

Objective
=========
1.0 R_BIOMASS = 0.12333946960920199

Uptake
------
Metabolite Reaction      Flux  C-Number C-Flux
     ca2_e EX_ca2_e 0.0003947         0  0.00%
     fe3_e EX_fe3_e 0.0004194         0  0.00%
     fru_e EX_fru_e     6.096         0  0.00%
     h2s_e EX_h2s_e    0.0228         0  0.00%
       k_e   EX_k_e   0.08711         0  0.00%
     mg2_e EX_mg2_e   0.01254         0  0.00%
     nh4_e EX_nh4_e     1.338         0  0.00%
     nmn_e EX_nmn_e  0.002134         0  0.00%
      pi_e  EX_pi_e    0.2616         0  0.00%

Secretion
---------
Metabolite     Reaction    Flux  C-Number C-Flux
      ac_e      EX_ac_e  -10.15         0  0.00%
 biomass_c EX_biomass_c -0.1233         0  0.00%
     co2_e     EX_co2_e  -10.53         0  0.00%
      h2_e      EX_h2_e  -14.73         0  0.00%
     h2o_e     EX_h2o_e  -11.27         0  0.00%

In [11]:
#fructose + acetate (different objective)
with model:
    model.objective= 'R_BIOMASS'
    model.reactions.EX_cellulose_e.lower_bound = 0
    model.reactions.EX_cellulose_e.upper_bound = 0
    model.reactions.EX_cellobiose_e.lower_bound = 0
    model.reactions.EX_cellobiose_e.upper_bound = 0
    model.reactions.EX_fru_e.lower_bound = -6.0961
    model.reactions.EX_fru_e.upper_bound = -6.0961
    model.reactions.EX_ac_e.lower_bound = 1.789
    model.reactions.EX_ac_e.upper_bound = 1.789
    sol=model.optimize()
    print(model.summary())

Objective
=========
1.0 R_BIOMASS = 0.09540169419266528

Uptake
------
Metabolite Reaction      Flux  C-Number C-Flux
     ca2_e EX_ca2_e 0.0003053         0  0.00%
     fe3_e EX_fe3_e 0.0003244         0  0.00%
     fru_e EX_fru_e     6.096         0  0.00%
     h2s_e EX_h2s_e   0.01763         0  0.00%
       k_e   EX_k_e   0.06738         0  0.00%
     mg2_e EX_mg2_e  0.009702         0  0.00%
     nh4_e EX_nh4_e     1.035         0  0.00%
     nmn_e EX_nmn_e   0.00165         0  0.00%
      pi_e  EX_pi_e    0.2024         0  0.00%

Secretion
---------
Metabolite     Reaction    Flux  C-Number C-Flux
      ac_e      EX_ac_e  -1.789         0  0.00%
 biomass_c EX_biomass_c -0.0954         0  0.00%
     co2_e     EX_co2_e  -10.91         0  0.00%
    etoh_e    EX_etoh_e  -3.007         0  0.00%
      h2_e      EX_h2_e  -14.66         0  0.00%
     h2o_e     EX_h2o_e  -8.964         0  0.00%
    succ_e    EX_succ_e  -2.908         0  0.00%

In [12]:
#trying with the other objective
with model:
    model.objective= 'R_BIOMASScell'
    model.reactions.EX_cellulose_e.lower_bound = 0
    model.reactions.EX_cellulose_e.upper_bound = 0
    model.reactions.EX_cellobiose_e.lower_bound = 0
    model.reactions.EX_cellobiose_e.upper_bound = 0
    model.reactions.EX_fru_e.lower_bound = -6.0961
    model.reactions.EX_fru_e.upper_bound = -6.0961
    model.reactions.EX_ac_e.lower_bound = 1.789
    model.reactions.EX_ac_e.upper_bound = 1.789
    sol=model.optimize()
    print(model.summary())

Objective
=========
1.0 R_BIOMASScell = 0.09767697147781926

Uptake
------
Metabolite Reaction      Flux  C-Number C-Flux
     ca2_e EX_ca2_e 0.0003126         0  0.00%
     fe3_e EX_fe3_e 0.0003321         0  0.00%
     fru_e EX_fru_e     6.096         0  0.00%
     h2s_e EX_h2s_e   0.01455         0  0.00%
       k_e   EX_k_e   0.06899         0  0.00%
     mg2_e EX_mg2_e  0.009934         0  0.00%
     nh4_e EX_nh4_e     0.897         0  0.00%
     nmn_e EX_nmn_e   0.00169         0  0.00%
      pi_e  EX_pi_e    0.2072         0  0.00%

Secretion
---------
Metabolite      Reaction     Flux  C-Number C-Flux
      ac_e       EX_ac_e   -1.789         0  0.00%
cellmass_c EX_cellmass_c -0.09768         0  0.00%
     co2_e      EX_co2_e   -11.06         0  0.00%
    etoh_e     EX_etoh_e   -3.067         0  0.00%
      h2_e       EX_h2_e   -14.88         0  0.00%
     h2o_e      EX_h2o_e   -8.836         0  0.00%
    succ_e     EX_succ_e   -2.972         0  0.00%

In [13]:
#trying with other objective 
with model:
    model.objective = 'R_BIOMASS'
    model.reactions.EX_cellulose_e.lower_bound = 0
    model.reactions.EX_cellulose_e.upper_bound = 0
    model.reactions.EX_cellobiose_e.lower_bound = -2.2472
    model.reactions.EX_cellobiose_e.upper_bound = -2.2472
    model.reactions.EX_fru_e.lower_bound = 0
    model.reactions.EX_fru_e.upper_bound = 0
    model.reactions.EX_ac_e.lower_bound = 2.457
    model.reactions.EX_ac_e.upper_bound = 2.457
    sol=model.optimize()
    print(model.summary())

Objective
=========
1.0 R_BIOMASS = 0.07448384467243137

Uptake
------
  Metabolite        Reaction      Flux  C-Number C-Flux
       ca2_e        EX_ca2_e 0.0002383         0  0.00%
cellobiose_e EX_cellobiose_e     2.247         0  0.00%
       fe3_e        EX_fe3_e 0.0002532         0  0.00%
       h2s_e        EX_h2s_e   0.01377         0  0.00%
         k_e          EX_k_e   0.05261         0  0.00%
       mg2_e        EX_mg2_e  0.007575         0  0.00%
       nh4_e        EX_nh4_e    0.8079         0  0.00%
       nmn_e        EX_nmn_e  0.001289         0  0.00%
        pi_e         EX_pi_e     0.158         0  0.00%

Secretion
---------
Metabolite     Reaction     Flux  C-Number C-Flux
      ac_e      EX_ac_e   -2.457         0  0.00%
 biomass_c EX_biomass_c -0.07448         0  0.00%
     co2_e     EX_co2_e   -7.986         0  0.00%
    etoh_e    EX_etoh_e   -1.817         0  0.00%
      h2_e      EX_h2_e   -10.92         0  0.00%
     h2o_e     EX_h2o_e   -4.751         0  0.00%
    succ_e    EX_succ_e    -1.74         0  0.00%

In [37]:
#delet???
with model:
    model.objective = 'R_BIOMASS'
    model.reactions.EX_cellulose_e.lower_bound = 0
    model.reactions.EX_cellulose_e.upper_bound = 0
    model.reactions.EX_cellobiose_e.lower_bound = -12.8
    model.reactions.EX_cellobiose_e.upper_bound = -12.8
    model.reactions.EX_fru_e.lower_bound = 0
    model.reactions.EX_fru_e.upper_bound = 0
    model.reactions.EX_ac_e.upper_bound = 0
    model.reactions.EX_ac_e.lower_bound = 0
    model.reactions.EX_for_e.upper_bound = 0
    model.reactions.EX_for_e.lower_bound = 0
    model.reactions.EX_etoh_e.upper_bound = 0
    model.reactions.EX_etoh_e.lower_bound = 0
    model.reactions.EX_h2_e.upper_bound = 0
    model.reactions.EX_h2_e.lower_bound = 0
    model.reactions.EX_co2_e.upper_bound = 0
    model.reactions.EX_co2_e.lower_bound = 0
    sol=model.optimize()
    print(model.summary())

Objective
=========
1.0 R_BIOMASS = 0.311517411060081

Uptake
------
  Metabolite        Reaction      Flux  C-Number C-Flux
       ca2_e        EX_ca2_e 0.0009969         0  0.00%
cellobiose_e EX_cellobiose_e      12.8         0  0.00%
       fe3_e        EX_fe3_e  0.001059         0  0.00%
       h2s_e        EX_h2s_e   0.05758         0  0.00%
         k_e          EX_k_e      0.22         0  0.00%
       mg2_e        EX_mg2_e   0.03168         0  0.00%
       nh4_e        EX_nh4_e     12.24         0  0.00%
       nmn_e        EX_nmn_e  0.005389         0  0.00%
        pi_e         EX_pi_e    0.6608         0  0.00%

Secretion
---------
Metabolite     Reaction    Flux  C-Number C-Flux
   asp-l_e   EX_asp-l_e  -8.862         0  0.00%
 biomass_c EX_biomass_c -0.3115         0  0.00%
     h2o_e     EX_h2o_e  -42.27         0  0.00%
   lac-l_e   EX_lac-l_e  -29.28         0  0.00%
    succ_e    EX_succ_e  -3.948         0  0.00%

In [38]:
#delete??
with model:
    model.objective = 'R_BIOMASS'
    model.reactions.EX_cellulose_e.lower_bound = 0
    model.reactions.EX_cellulose_e.upper_bound = 0
    model.reactions.EX_cellobiose_e.lower_bound = -12.8
    model.reactions.EX_cellobiose_e.upper_bound = -12.8
    model.reactions.EX_fru_e.lower_bound = 0
    model.reactions.EX_fru_e.upper_bound = 0
   # model.reactions.R_FDXHASE.lower_bound = 0 
   # model.reactions.R_FDXHASE.upper_bound = 0 
   # model.reactions.EX_etoh_e.lower_bound = 25.9697
   # model.reactions.EX_etoh_e.upper_bound = 25.9697
    sol=model.optimize()
    print(model.summary())

Objective
=========
1.0 R_BIOMASS = 0.5179525306336287

Uptake
------
  Metabolite        Reaction     Flux  C-Number C-Flux
       ca2_e        EX_ca2_e 0.001657         0  0.00%
cellobiose_e EX_cellobiose_e     12.8         0  0.00%
       fe3_e        EX_fe3_e 0.001761         0  0.00%
       h2s_e        EX_h2s_e  0.09573         0  0.00%
         k_e          EX_k_e   0.3658         0  0.00%
       mg2_e        EX_mg2_e  0.05268         0  0.00%
       nh4_e        EX_nh4_e    5.618         0  0.00%
       nmn_e        EX_nmn_e 0.008961         0  0.00%
        pi_e         EX_pi_e    1.099         0  0.00%

Secretion
---------
Metabolite     Reaction   Flux  C-Number C-Flux
      ac_e      EX_ac_e -42.62         0  0.00%
 biomass_c EX_biomass_c -0.518         0  0.00%
     co2_e     EX_co2_e -44.22         0  0.00%
      h2_e      EX_h2_e -61.85         0  0.00%
     h2o_e     EX_h2o_e -34.53         0  0.00%